services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: dbw_user
      POSTGRES_PASSWORD: dbw_pass
      POSTGRES_DB: dbw_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data:
